version: "3"
services:
  netflixshow:
    image: netflixshow-lat
    ports:
      - "8082:8080"
    networks:
      - netflix-network
    depends_on:
      - mysqldb

    mysqldb:
      image: mysql:8
      networks:
        - netflix-network
      environment:
        - MYSQL_ROOT_PASSWORD=Griezmann@17
        - MYSQL_DATABASE=hux

networks:
  netflix-network: